### ISSUE TITLE
MVP - API Research

### ISSUE THREAD

**Issue by PrimalOrB** [PrimalOrB/gamer-match#11]
- [x] define what information we can get
- [x] determine how we can use the information that we get
- [x] acquire steam API key

**Comment by powerar** [comment]
We can use the data we receive from the API as follows:
1. POST game data to the game table
2. POST user data to the User table
3. POST user game data to the usergame table

Game data contains:
1. AppId
2. Game Name
3. IMG Icon
4. IMG logo

User Data contains:
1. SteamID
2. Username

UserGameData contains:
1. SteamId
2. AppId
3. Playtime

We will need the following links between the tables:
1. User SteamID is FK to the UserGame table via SteamId
2. Game AppID is FK to the UserGame table via AppId

To match players the query would look something like:
SELECT * FROM user
JOIN usergame ON user.steamid = usergame.steamid
JOIN game ON game.appid = usergame.appid
WHERE usergame.appid IN (SELECT usergame.appid FROM usergame WHERE steamId = "logged in user steamId")
ORDER BY usergame.playtime;

The goal would be to display the users who have the same games played in the last two weeks, ordered by the playtime.

**Comment by powerar** [comment]
DB Diagram
![image](https://user-images.githubusercontent.com/78888642/119878452-2103dc00-bef8-11eb-9484-08eec1c46872.png)

**Comment by PrimalOrB** [comment]
double check the existing db setup. I believe the schema was working as desired (can be seeded and tested via insomnia)

can see all users, and what games they play

can see alll games, and see what users play them

can see all user games, and who the users are / what the games are
